### ISSUE TITLE
Create a tag version

### ISSUE THREAD

**Issue by yamashi** [0x1F9F1/mem#2]
Hello,

I am trying to integrate your lib as package in the xmake build system but the lack of tags makes it difficult. Would it be possible to create a tag? 1.0.0 or whatever version number you think makes sense so that we can reference it?

See: https://github.com/xmake-io/xmake-repo/blob/master/packages/m/mem/xmake.lua

Thanks!

**Comment by 0x1F9F1** [comment]
Is this still needed? Looks like you added a 0.1.0 version for the current commit.

**Comment by yamashi** [comment]
Yea it's a "fake" version number, it's up to you it works that way for now

**Comment by 0x1F9F1** [comment]
Sorry it took so long, but there is now a 1.0.0 tag
